apiVersion: v1
kind: ConfigMap
metadata:
  name: security-config
  namespace: backend
data:
  application.yml: |
    server:
      port: 8085

    spring:
      application:
        name: SECURITY-SERVICE
      redis:
        host: redis-service.database-namespace.svc.cluster.local
        port: 6379

    eureka:
      client:
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}