apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security
  template:
    metadata:
      labels:
        app: security
    spec:
      containers:
        - name: security
          image: security-service:0.3
          imagePullPolicy: Never
          ports:
            - containerPort: 8085
          env:
            - name: EUREKA_SERVER_URL
              value: "http://discovery-server.backend.svc.cluster.local:8761/eureka/"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config/application.yml
              subPath: application.yml
      volumes:
        - name: config-volume
          configMap:
            name: security-config

---
apiVersion: v1
kind: Service
metadata:
  name: security-service
  namespace: backend
spec:
  type: ClusterIP  # Or ClusterIP if using Ingress
  selector:
    app: security
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP