server:
  port: 8085

spring:
#  redis:
#    host: redis-service.database-namespace.svc.cluster.local
#    port: 6379
  application:
    name: security-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server.backend:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: false
#    hostname: user-service.backend

#eureka:
#  client:
#    enabled: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://discovery-server.backend:8761/eureka/



